# Generated by Django 5.2.7 on 2025-11-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo / Razão Social')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail')),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True, verbose_name='CPF/CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('responsavel_nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Responsável')),
                ('responsavel_cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF do Responsável')),
                ('responsavel_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail do Responsável')),
            ],
            options={
                'db_table': 'vendas_cliente',
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Forma de Pagamento')),
            ],
            options={
                'verbose_name': 'Forma de Pagamento',
                'verbose_name_plural': 'Formas de Pagamento',
                'db_table': 'vendas_formapagamento',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Base (Honorários Iniciais)')),
                ('tipo_comissao', models.CharField(choices=[('P', 'Percentual'), ('F', 'Valor Fixo')], default='P', max_length=1, verbose_name='Tipo de Comissão')),
                ('valor_comissao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Comissão')),
                ('valor_entrada_sugerido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Entrada Sugerida')),
                ('num_parcelas_sugerido', models.IntegerField(blank=True, null=True, verbose_name='Nº de Parcelas Sugerido')),
                ('valor_parcela_sugerido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Parcela Sugerido')),
                ('valor_exito_sugerido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Êxito Sugerido')),
                ('valor_aporte_sugerido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Aporte Sugerido')),
            ],
            options={
                'db_table': 'vendas_produto',
            },
        ),
    ]
