# Generated by Django 5.2.7 on 2025-11-10 23:18

import django.db.models.deletion
import vendas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo / Razão Social')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail')),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True, verbose_name='CPF/CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('responsavel_nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Responsável')),
                ('responsavel_cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF do Responsável')),
                ('responsavel_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail do Responsável')),
            ],
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Forma de Pagamento')),
            ],
            options={
                'verbose_name': 'Forma de Pagamento',
                'verbose_name_plural': 'Formas de Pagamento',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Base (Honorários Iniciais)')),
                ('tipo_comissao', models.CharField(choices=[('P', 'Percentual'), ('F', 'Valor Fixo')], default='P', max_length=1, verbose_name='Tipo de Comissão')),
                ('valor_comissao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Comissão')),
                ('valor_entrada_sugerido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Entrada Sugerida')),
                ('num_parcelas_sugerido', models.IntegerField(blank=True, null=True, verbose_name='Nº de Parcelas Sugerido')),
                ('valor_parcela_sugerido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Parcela Sugerido')),
                ('valor_exito_sugerido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Êxito Sugerido')),
                ('valor_aporte_sugerido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Aporte Sugerido')),
            ],
        ),
        migrations.CreateModel(
            name='LotePagamentoComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField(verbose_name='Início do Período')),
                ('periodo_fim', models.DateField(verbose_name='Fim do Período')),
                ('data_fechamento', models.DateTimeField(auto_now_add=True, verbose_name='Data de Fechamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago_parcialmente', 'Pago Parcialmente'), ('pago_integralmente', 'Pago Integralmente')], default='pendente', max_length=20)),
                ('total_comissoes', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Devido (R$)')),
                ('total_pago_efetivamente', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Pago (R$)')),
                ('responsavel_fechamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_fechados', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo Fechamento')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_pagos', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor a Pagar')),
            ],
            options={
                'verbose_name': 'Lote de Pagamento de Comissão',
                'verbose_name_plural': 'Lotes de Pagamento de Comissão',
                'ordering': ['-data_fechamento'],
            },
        ),
        migrations.CreateModel(
            name='AnexoLoteComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anexo_nf_vendedor', models.FileField(blank=True, null=True, upload_to=vendas.models.get_anexo_transacao_path, verbose_name='Anexo (Nota Fiscal do Vendedor)')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Original/Descrição')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos_lote', to='vendas.lotepagamentocomissao')),
            ],
        ),
        migrations.CreateModel(
            name='TransacaoPagamentoComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pagamento')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Pago (R$)')),
                ('anexo_comprovativo_pagamento', models.FileField(blank=True, null=True, upload_to=vendas.models.get_anexo_transacao_path, verbose_name='Anexo (Comprovativo de Pagamento)')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Original/Descrição')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes_pagamento', to='vendas.lotepagamentocomissao')),
                ('responsavel_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo Pagamento')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honorarios', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Honorários Totais (Calculado)')),
                ('valor_entrada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Entrada (Negociado)')),
                ('num_parcelas', models.IntegerField(blank=True, null=True, verbose_name='Nº de Parcelas (Negociado)')),
                ('valor_parcela', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Parcela (Negociado)')),
                ('valor_exito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Honorários no Êxito (Negociado)')),
                ('valor_aporte', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor de Aporte (Negociado)')),
                ('data_venda', models.DateTimeField(auto_now_add=True, verbose_name='Data da Venda')),
                ('status_venda', models.CharField(choices=[('iniciada', 'Iniciada'), ('em_negociacao', 'Em Negociação'), ('aguardando_pagamento', 'Aguardando Pagamento'), ('em_contrato', 'Em Contrato'), ('concluida', 'Concluída'), ('perdida', 'Perdida')], default='iniciada', max_length=30)),
                ('status_pagamento', models.CharField(choices=[('pendente', 'Pendente (Sem comprovante)'), ('aguardando_validacao', 'Aguardando Validação'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='pendente', max_length=30)),
                ('status_contrato', models.CharField(choices=[('nao_gerado', 'Não Gerado'), ('gerado', 'Gerado (Pendente Assinatura)'), ('assinado', 'Assinado'), ('finalizado', 'Finalizado')], default='nao_gerado', max_length=30)),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações Internas')),
                ('comissao_personalizada_valor', models.DecimalField(blank=True, decimal_places=2, help_text='Se preenchido, este valor substitui todas as outras regras de cálculo.', max_digits=10, null=True, verbose_name='Comissão Personalizada (R$)')),
                ('comissao_calculada_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Comissão Final Calculada (R$)')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='vendas.cliente', verbose_name='Cliente')),
                ('forma_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vendas.formapagamento', verbose_name='Forma de Pagamento')),
                ('lote_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='vendas.lotepagamentocomissao', verbose_name='Lote de Pagamento')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='vendas.produto', verbose_name='Produto')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('comprovante', 'Comprovante de Pagamento'), ('contrato', 'Contrato'), ('nota_fiscal', 'Nota Fiscal')], default='comprovante', max_length=20)),
                ('arquivo', models.FileField(upload_to=vendas.models.get_anexo_upload_path, verbose_name='Arquivo')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Original')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data do Upload')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='vendas.venda', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Anexo da Venda',
                'verbose_name_plural': 'Anexos da Venda',
            },
        ),
        migrations.CreateModel(
            name='RegraComissaoVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comissao', models.CharField(choices=[('P', 'Percentual'), ('F', 'Valor Fixo')], default='P', max_length=1, verbose_name='Tipo de Comissão (Exceção)')),
                ('valor_comissao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Comissão (Exceção)')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_comissao_excecao', to='vendas.produto', verbose_name='Produto Específico')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_comissao', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor Específico')),
            ],
            options={
                'verbose_name': 'Regra de Exceção de Comissão',
                'verbose_name_plural': 'Regras de Exceção de Comissão',
                'unique_together': {('vendedor', 'produto')},
            },
        ),
    ]
