# Generated by Django 5.2.7 on 2025-11-12 14:09

import django.db.models.deletion
import vendas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comissoes', '0001_initial'),
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honorarios', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Honorários Totais (Calculado)')),
                ('valor_entrada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Entrada (Negociado)')),
                ('num_parcelas', models.IntegerField(blank=True, null=True, verbose_name='Nº de Parcelas (Negociado)')),
                ('valor_parcela', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Parcela (Negociado)')),
                ('valor_exito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Honorários no Êxito (Negociado)')),
                ('valor_aporte', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor de Aporte (Negociado)')),
                ('data_venda', models.DateTimeField(auto_now_add=True, verbose_name='Data da Venda')),
                ('status_venda', models.CharField(choices=[('iniciada', 'Iniciada'), ('em_negociacao', 'Em Negociação'), ('aguardando_pagamento', 'Aguardando Pagamento'), ('em_contrato', 'Em Contrato'), ('concluida', 'Concluída'), ('perdida', 'Perdida')], default='iniciada', max_length=30)),
                ('status_pagamento', models.CharField(choices=[('pendente', 'Pendente (Sem comprovante)'), ('aguardando_validacao', 'Aguardando Validação'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='pendente', max_length=30)),
                ('status_contrato', models.CharField(choices=[('nao_gerado', 'Não Gerado'), ('gerado', 'Gerado (Pendente Assinatura)'), ('assinado', 'Assinado'), ('finalizado', 'Finalizado')], default='nao_gerado', max_length=30)),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações Internas')),
                ('comissao_personalizada_valor', models.DecimalField(blank=True, decimal_places=2, help_text='Se preenchido, este valor substitui todas as outras regras de cálculo.', max_digits=10, null=True, verbose_name='Comissão Personalizada (R$)')),
                ('comissao_calculada_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Comissão Final Calculada (R$)')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='common.cliente', verbose_name='Cliente')),
                ('forma_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.formapagamento', verbose_name='Forma de Pagamento')),
                ('lote_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='comissoes.lotepagamentocomissao', verbose_name='Lote de Pagamento')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='common.produto', verbose_name='Produto')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('comprovante', 'Comprovante de Pagamento'), ('contrato', 'Contrato'), ('nota_fiscal', 'Nota Fiscal')], default='comprovante', max_length=20)),
                ('arquivo', models.FileField(upload_to=vendas.models.get_anexo_upload_path, verbose_name='Arquivo')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Original')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data do Upload')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='vendas.venda', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Anexo da Venda',
                'verbose_name_plural': 'Anexos da Venda',
            },
        ),
    ]
