# Generated by Django 5.2.7 on 2025-11-11 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('valor_meta', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor da Meta (R$)')),
                ('vendedor', models.ForeignKey(blank=True, help_text='Se deixado em branco, esta será a meta GERAL da empresa para o período.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor (Individual)')),
            ],
            options={
                'verbose_name': 'Meta de Venda',
                'verbose_name_plural': 'Metas de Venda',
                'ordering': ['data_inicio', 'vendedor'],
                'unique_together': {('data_inicio', 'data_fim', 'vendedor')},
            },
        ),
    ]
