# Generated by Django 5.2.7 on 2025-11-11 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('vendas', '0002_metavenda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metavenda',
            options={'ordering': ['data_inicio', 'vendedor', 'grupo'], 'verbose_name': 'Meta de Venda', 'verbose_name_plural': 'Metas de Venda'},
        ),
        migrations.AlterUniqueTogether(
            name='metavenda',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='metavenda',
            name='grupo',
            field=models.ForeignKey(blank=True, help_text='Selecione um grupo para uma meta de equipa.', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Equipa (Grupo)'),
        ),
        migrations.AlterField(
            model_name='metavenda',
            name='vendedor',
            field=models.ForeignKey(blank=True, help_text='Selecione um vendedor para uma meta individual.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor (Individual)'),
        ),
        migrations.AlterUniqueTogether(
            name='metavenda',
            unique_together={('data_inicio', 'data_fim', 'vendedor', 'grupo')},
        ),
    ]
