# Generated by Django 5.2.7 on 2025-11-13 17:51

import comissoes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LotePagamentoComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField(verbose_name='Início do Período')),
                ('periodo_fim', models.DateField(verbose_name='Fim do Período')),
                ('data_fechamento', models.DateTimeField(auto_now_add=True, verbose_name='Data de Fechamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago_parcialmente', 'Pago Parcialmente'), ('pago_integralmente', 'Pago Integralmente')], default='pendente', max_length=20)),
                ('total_comissoes', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Devido (R$)')),
                ('total_pago_efetivamente', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Pago (R$)')),
                ('responsavel_fechamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_fechados', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo Fechamento')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_pagos', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor a Pagar')),
            ],
            options={
                'verbose_name': 'Lote de Pagamento de Comissão',
                'verbose_name_plural': 'Lotes de Pagamento de Comissão',
                'db_table': 'vendas_lotepagamentocomissao',
                'ordering': ['-data_fechamento'],
            },
        ),
        migrations.CreateModel(
            name='AnexoLoteComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anexo_nf_vendedor', models.FileField(blank=True, null=True, upload_to=comissoes.models.get_anexo_transacao_path, verbose_name='Anexo (Nota Fiscal do Vendedor)')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Original/Descrição')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos_lote', to='comissoes.lotepagamentocomissao')),
            ],
            options={
                'db_table': 'vendas_anexolotecomissao',
            },
        ),
        migrations.CreateModel(
            name='TransacaoPagamentoComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pagamento')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Pago (R$)')),
                ('anexo_comprovativo_pagamento', models.FileField(blank=True, null=True, upload_to=comissoes.models.get_anexo_transacao_path, verbose_name='Anexo (Comprovativo de Pagamento)')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Original/Descrição')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes_pagamento', to='comissoes.lotepagamentocomissao')),
                ('responsavel_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo Pagamento')),
            ],
            options={
                'db_table': 'vendas_transacaopagamentocomissao',
            },
        ),
        migrations.CreateModel(
            name='MetaVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('valor_meta', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor da Meta (R$)')),
                ('grupo', models.ForeignKey(blank=True, help_text='Selecione um grupo para uma meta de equipa.', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Equipa (Grupo)')),
                ('vendedor', models.ForeignKey(blank=True, help_text='Selecione um vendedor para uma meta individual.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor (Individual)')),
            ],
            options={
                'verbose_name': 'Meta de Venda',
                'verbose_name_plural': 'Metas de Venda',
                'db_table': 'vendas_metavenda',
                'ordering': ['data_inicio', 'vendedor', 'grupo'],
                'unique_together': {('data_inicio', 'data_fim', 'vendedor', 'grupo')},
            },
        ),
        migrations.CreateModel(
            name='RegraComissaoVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comissao', models.CharField(choices=[('P', 'Percentual'), ('F', 'Valor Fixo')], default='P', max_length=1, verbose_name='Tipo de Comissão (Exceção)')),
                ('valor_comissao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Comissão (Exceção)')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_comissao_excecao', to='common.produto', verbose_name='Produto Específico')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_comissao', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor Específico')),
            ],
            options={
                'verbose_name': 'Regra de Exceção de Comissão',
                'verbose_name_plural': 'Regras de Exceção de Comissão',
                'db_table': 'vendas_regracomissaovendedor',
                'unique_together': {('vendedor', 'produto')},
            },
        ),
    ]
